### ISSUE TITLE
res下style文件夹缺失

### ISSUE THREAD

**Issue by XC-Qan** [HaoduyouduStudio/DailyNotes#1]
如题

p.s. : 请在本地用git工具push，不要直接在网站上上传3qxx

**Comment by MengXi2021** [comment]
收到，将在1小时之内补全style文件，上传完整之后我们会联系您，确认无误后我们/您将会Close此Issues

**Comment by MengXi2021** [comment]
style文件应该已经push，请检查
p.s. : 为什么git也会提示上传文件过多(((

**Comment by HaoduyouduDev** [comment]
> style文件应该已经push，请检查 p.s. : 为什么git也会提示上传文件过多(((

这这这，你用错git push了吧
有空我自己再上传一遍最新版
你们现在用的都不是最新版

**Comment by MengXi2021** [comment]
此lssues已close，若有疑问请联系support@zhunote.cn或联系我们的开发者（HaoduyouduDev）
